- name: rep jessie
  apt:
    name: "{{ item }}"
    update_cache: yes 
    state: installed
  with_items:
    - "apt-transport-https" 
    - "ca-certificates" 
    - "curl" 
    - "gnupg2" 
    - "software-properties-common"

- name: add key
  sudo: yes
  apt_key:
    validate_certs: no
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add rep
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable
    state: present

- name: docker install
  apt: 
    name: docker-ce 
    update_cache: yes 
    state: installed

- name: Start docker on boot
  service: 
    name: docker
    state: started 
    enabled: yes


