- name: install node.js
  apt:
    name: "{{ item }}"
  with_items:
    - "build-essential"
    - "curl"
    - "bzip2"
    - "gawk"
    - "gcc"
    - "make"
    - "zlib1g-dev" 
    - "libreadline6-dev" 
    - "libyaml-0-2" 
    - "libyaml-dev" 
    - "automake" 
    - "libtool" 
    - "libpq-dev" 
    - "host" 
    - "g++" 
    - "git" 
    - "libarchive-dev" 
    - "libsqlite3-dev" 
    - "sqlite3" 
    - "libgdbm-dev" 
    - "libncurses5-dev" 
    - "bison" 
    - "pkg-config" 
    - "libffi-dev" 
    - "libcurl4-openssl-dev" 
    - "libxml2-dev"
    - "libgmp3-dev"
    - "libssl-dev"
  sudo: yes

- name: install 
  shell: bash -lc "curl https://raw.githubusercontent.com/creationix/nvm/v0.16.1/install.sh | sh"
  become: true
  become_user: rails

- name: install node 6.10.3
  shell: bash -c "source ~/.nvm/nvm.sh && nvm install 6.10.3 && nvm alias default 6.10.3"
  become: true
  become_user: rails

- name: install webpack
  npm:
   name: weback
  become: true
  become_user: rails
